server:
  port: 10111
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: git@github.com:BestWishes/engineConfig.git
          default-label: master
    consul:
      port: 8500
      host: 127.0.0.1
